services:
  website:
    image: node:20-alpine
    working_dir: /app
    environment:
      VITE_API_URL: ${VITE_API_URL:-http://localhost:4000/api}
      NODE_ENV: development
    volumes:
      - ./:/app
      - website_node_modules:/app/node_modules
      - website_vite_cache:/root/.cache/vite
    ports:
      - "4173:4173"
    depends_on:
      api:
        condition: service_started

volumes:
  website_node_modules: null
  website_vite_cache: null
