name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build-and-verify:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
      ALLOWED_ORIGIN: ${{ secrets.ALLOWED_ORIGIN }}
      ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
      ADMIN_PASSWORD_HASH: ${{ secrets.ADMIN_PASSWORD_HASH }}
      DB_SSL: ${{ secrets.DB_SSL }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install root dependencies (include devDependencies)
        run: HUSKY=0 npm ci --include=dev

      - name: Install server dependencies (include devDependencies)
        run: HUSKY=0 npm ci --include=dev
        working-directory: server

      - name: Verify production environment configuration
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: npm run verify:env

      - name: Run lint
        run: npm run lint

      - name: Run tests
        run: npm run test:all

      - name: Run frontend tests with coverage
        run: npm run coverage:run

      - name: Run server tests with coverage
        run: npm run coverage:run:server
        working-directory: server

      - name: Merge coverage reports
        run: npm run coverage:merge

      - name: Upload merged coverage (lcov + html)
        uses: actions/upload-artifact@v4
        with:
          name: coverage-merged
          path: coverage/merged
